### ISSUE TITLE
Doubt of noob

### ISSUE THREAD

**Issue by hernanChain** [kimsawol/english-irregular-verbs#1]
Hi, Can you say me how can I use your program of irregular-verbs?

**Comment by kimsawol** [comment]
Sure!

You can choose whether the verbs are displayed in order or randomly:
```
Type 'y' to learn the English irregular verbs randomly.
Type any other letter to continue: y
```

And you can choose if the script shows you infinite words:
```
Type 'y' to run the script infinitely.
Type any other letter to continue: y
```

You can read and listen to the pronunciation. By the way, you have to write the verb to continue:
```
Irregular verb: choose
Spelling: c h o o s e 
Tenses: infinitive
Type the word 'choose': choose
```

I know my script needs magic. I accept improvements! Do you have any question?

**Comment by kimsawol** [comment]
I recommend that you use [PyCharm Community](https://www.jetbrains.com/pycharm/download).
Create a virtual environment:
`python3 -m venv ./venv`
And install the requirements:
`pip install --requirement requirements.txt`
